"""restructure_alembicVersions

Revision ID: 70465b6171dc
Revises: 
Create Date: 2026-07-15 03:31:59.726117
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '70465b6171dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_estudio',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('racha_dias', sa.Integer(), server_default='0', nullable=True),
    sa.Column('tiempo_estudio_segundos', sa.Integer(), server_default='0', nullable=True),
    sa.Column('tiempo_estudio_reiniciado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_estudio')
    # ### end Alembic commands ###
